### ISSUE TITLE
Dart SDK version is 2.1.0-dev.0.0.flutter-be6309690f

### ISSUE THREAD

**Issue by deibyRodri** [gbrvalerio/carousel#10]
I recently updated my version of Dart and when I run the app the console shows the next message 

> The current Dart SDK version is 2.1.0-dev.0.0.flutter-be6309690f.
> Because kaptarapp depends on carousel >=0.1.0 which requires SDK version <2.0.0, version solving failed.
> pub get failed (1)

thanks in advance for your help.

**Comment by hahn** [comment]
i got same error, after update flutter to new version. 
temporary solution: copy `carousel.dat` to your project and disable this plugin.

**Comment by NewITCorp** [comment]
I vote this up to the author, please upgrade flutter SDK version.

**Comment by lipengda** [comment]
same error

**Comment by brammittendorff** [comment]
Same error please fix this.
